#!/usr/bin/php
<?php
require_once 'Console/Getopt.php';

global $syslog, $confdir, $debug;
$syslog = "/var/log/syslog";
$confdir = "/etc/ew-firewall";

$arguments = parse_arguments();
debug_dump_configuration();

function debug_dump_configuration() {
    global $syslog, $confdir;
    debug("Syslog path: $syslog");
    debug("Configuration directory: $confdir");
}

function perror($message) {
    file_put_contents('php://stderr', $message . "\n");
}

function showUsage() {
    perror("Usage: ew-firewall [options] <rules|blocked>");
    exit(1);
}

// Configuration checks
if (count($arguments) != 1) {
    showUsage();
}
if (!file_exists($syslog)) {
    perror("Error: syslog file '$syslog' does not exist");
    exit(1);
}
if (!is_readable($syslog)) {
    perror("Error: permission denied while reading '$syslog'");
    exit(1);
}
if (!is_dir($confdir)) {
    perror("Error: '$confdir' does not exist or is not a directory");
    exit(1);
}
if (!is_readable($confdir)) {
    perror("Error: permission denied while reading '$confdir'");
    exit(1);
}

debug("Arguments: " . implode(' ', $arguments));
switch ($arguments[0]) {
    case 'rules':
        loadRules();
        break;
    case 'blocked':
        showBlocked();
        break;
    default:
        showUsage();
        break;
}

function debug($message) {
    global $debug;
    if (!$debug) return;
    perror($message);
}

function parse_arguments() {
    global $syslog, $confdir, $debug;

    $cg = new Console_Getopt();
    $args = $cg->readPHPArgv();
    array_shift($args);

    $shortopts = "c:dhs:";
    $longopts  = array(
        "conf-dir:",      // Configuration directory
        "debug",          // Enable debugging
        "help",           // Show help/usage
        "syslog:",        // Syslog path
    );
    $result = $cg->getopt2($args, $shortopts, $longopts);
    if (PEAR::isError($result)) {
        perror("Error: " . $result->getMessage());
        exit(1);
    }
    list($result, $arguments) = $result;
    $options = array();
    foreach($result as $value) {
        $options[$value[0]] = $value[1];
    }

    foreach($options as $option=>$value) {
        switch($option) {
            case 'c':
            case 'conf-dir':
                $confdir = $value;
                break;

            case 'd':
            case 'debug':
                $debug = true;
                break;

            case 'h':
            case 'help':
                showUsage();
                exit(1);

            case 's':
            case 'syslog':
                $syslog = $value;
        }
    }

    // Cleanup argv from the already-processed options
    return $arguments;
}


function fread_until($file, $offset, $limit) {
    #echo "Reading $file from $offset until $limit\n";
    $fh = fopen($file, 'r');
    fseek($fh, $offset);
    $buf = fread($fh, $limit);
    fclose($fh);
    return $buf;
}

function getUnprocessedLines($logfile, $bytesdir) {
    $bytesfile = $bytesdir . '/' . basename($logfile) . '.bytes';

    $total_bytes = filesize($logfile);
    $last_bytes = (int)@file_get_contents($bytesfile);
    $lines = '';
    if ($total_bytes < $last_bytes) {
        // Logfile has been rotated, so we have to read the remainder from the old file
        $lines = fread_until("$logfile.0", $last_bytes, filesize("$logfile.0"));
        $last_bytes = 0;
    } elseif ($total_bytes == $last_bytes) {
        return array();
    }
    $lines .= fread_until($logfile, $last_bytes, $total_bytes);

    # Compute and update the last read byte offset
    file_put_contents($bytesfile, $total_bytes);

    $lines = explode("\n", trim($lines));
    return $lines;
}

function showBlocked() {
    global $syslog, $confdir;

    $drops = array(); $logs = array();
    $lines = getUnprocessedLines($syslog, $confdir);
    foreach($lines as $line) {
        if (strstr($line, 'ewf-drop')) {
            $drop = processEwfLine($line);
            $drops[$drop['time']] = $drop;
        } elseif (strstr($line, 'ewf-log')) {
            $log = processEwfLine($line);
            $logs[$log['time']] = $log;
        } elseif (strstr($line, 'tinyproxy')) {
            $drop = processTpLine($line);
            $drops[$drop['time']] = $drop;
        }
    }

    ksort($drops);
    printBlocks($drops, $logs);
}


function processTpLine($line) {
    debug("Processing tinyproxy line: $line");
    $f = preg_split('/[\s]+/', $line, 4);
    $date = $f[0] . ' ' . $f[1] . ' ' . $f[2];
    if (preg_match('/Proxying refused on filtered url "(\S+)"/', $f[3], $matches)) {
        return array('type' => 'tp', 'time' => strtotime($date), 'url' => $matches[1]);
    } else if (preg_match('/error "\S+"/', $f[3], $matches)) {
        return array('type' => 'tp', 'time' => strtotime($date), 'url' => $matches[0]);
    }
    return array('type' => 'none', 'time' => 0);
}

function printBlocks($drops, $logs) {
    foreach($drops as $drop) {
        switch ($drop['type']) {
            case 'tp':
                printTpDrop($drop, $logs);
                break;
            case 'ewf':
                printEwfDrop($drop, $logs);
                break;
        }
    }
}

function printEwfDrop($drop, $logs) {
    echo strftime('%c', $drop['time'])
       . ' [D] blocked ' . $drop['uname']
       . ' (' . $drop['uuid'] . ') -> ' . $drop['dest'] . ':' . $drop['port'] . "\n";
}
function printTpDrop($reject, $logs) {
    if (isset($logs[$reject['time']])) {
        $drop = $logs[$reject['time']];
        echo strftime('%c', $drop['time'])
           . ' [P] blocked ' . $drop['uname']
           . ' (' . $drop['uuid'] . ') -> ' . $reject['url'] . "\n";
    } else {
        echo strftime('%c', $reject['time'])
           . ' Proxy blocked unknown () -> ' . $reject['url'] . "\n";
    }
}

function processEwfLine($line) {
    $f = preg_split('/[\s]+/', $line, 4);
    $date = $f[0] . ' ' . $f[1] . ' ' . $f[2];
    preg_match('/DST=([^\s]+)/', $line, $matches);
    $dest = $matches[1];
    preg_match('/DPT=([^\s]+)/', $line, $matches);
    $port = $matches[1];
    preg_match('/UID=([^\s]+)/', $line, $matches);
    $uuid = $matches[1];
    $uinfo = posix_getpwuid($uuid);
    $uname = explode('/', $uinfo['dir']); $uname = $uname[count($uname)-1];

    return array(
        'type' => 'ewf', 'time' => strtotime($date), 'uname' => $uname, 'uuid' => $uuid, 'dest' => $dest, 'port' => $port
    );
}

function loadRules() {
    global $confdir;

    $lines = file("$confdir/rules");
    foreach($lines as $line) {
        $line = trim($line);
        if (empty($line) || $line[0] == "#") continue;

        $rule = '${IPTABLES} -A EW_OUTPUT -p tcp ';
        $fields = preg_split('/[\s]+/', $line);
        if ($fields[1] != '*') $rule .= '-m owner --uid-owner ' . $fields[1] . ' ';
        if ($fields[2] != '*') $rule .= '-d ' . $fields[2] . ' ';
        if ($fields[3] != '*') $rule .= '--dport ' . $fields[3] . ' ';
        if ($fields[0] == 'I') $rule .= '-j REJECT';
        if ($fields[0] == 'A') $rule .= '-j RETURN';
        echo $rule . "\n";
    }
}

